server:
  port: 8010

spring:
  application:
    name: service-todo
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      server-addr: 127.0.0.1:8848

  config:
    import: nacos:shared-variable.properties


