server:
  port: 8020

spring:
  application:
    name: service-post
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
  config:
    import: nacos:shared-variable.properties