server:
  port: 8000

spring:
  application:
    name: service-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
  config:
    import: nacos:shared-variable.properties

feign:
  sentinel:
    enabled: true



